
############
## Project 
############
name: FastlanePlayground

############
## Options
############
## In this part we will override some project properties

options:
  minimumXcodeGenVersion: 2.41.0
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.0"

#############
## Settings
#############

settings:
  CURRENT_PROJECT_VERSION: "1"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  MARKETING_VERSION: "1.0"
  SWIFT_STRICT_CONCURRENCY: complete
  SWIFT_VERSION: "6.0"

############
## Packages
############
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.8.1

############
## Targets
############

targets:
  Codes:
    type: application 
    platform: iOS
    supportedDestinations: [iOS]
    deploymentTarget: "17.0"
    sources:
      - path: ./Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.alvinh.FastlanePlayground"
      SWIFT_STRICT_CONCURRENCY: complete
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight
        ]
        UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
      - package: Firebase
        products:
          - FirebaseCore
  UnitTests:
    type: bundle.unit-test
    platform: iOS
    supportedDestinations: [iOS]
    sources: ./UnitTests
    dependencies:
      - target: Codes
      - package: Firebase
        products:
          - FirebaseCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.alvinh.unittests"
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_STRICT_CONCURRENCY: complete
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  UITests:
    type: bundle.ui-testing
    platform: iOS
    supportedDestinations: [iOS]
    sources: ./UITests
    dependencies:
      - target: Codes
      - package: Firebase
        products:
          - FirebaseCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.alvinh.uitests"
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_STRICT_CONCURRENCY: complete
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO

schemes:
  FastlanePlayground:
    build:
      targets:
        Codes: all
    test:
      targets:
        - UnitTests
        - UITests
    run:
      config: Debug
      arguments:
        environmentVariables:
          ENABLE_LOGGING: YES