# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Constant Values
BUILD_DATA_PATH = "build"
DERIVED_DATA_PATH = "derived_data"
BUILD_OUTPUT_DIRECTORY = "build_outputs"
TEST_OUTPUT_DIRECTORY = "test_outputs"
PACKAGES_PATH = "packages_cache"
RESULT_BUNDLE_PATH = "test_outputs/TestResults.xcresult"
DESTINATION = "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro"
SCHEME = "FastlanePlayground"
WORKSPACE = "FastlanePlayground.xcworkspace"

platform :ios do
  desc "Build the iOS app"
  lane :build_tests do
    scan(
      buildlog_path: BUILD_DATA_PATH,
      build_for_testing: true,
      cloned_source_packages_path: PACKAGES_PATH,
      configuration: "Debug",
      derived_data_path: DERIVED_DATA_PATH,
      destination: DESTINATION,
      output_directory: BUILD_OUTPUT_DIRECTORY,
      output_xctestrun: true,
      scheme: SCHEME,
      workspace: WORKSPACE
    )
    copy_artifacts(
      target_path: BUILD_OUTPUT_DIRECTORY,
      artifacts: ["#{DERIVED_DATA_PATH}/Build/Products/*"]
    )
  end

  desc "Run unit tests without rebuilding"
  lane :run_unit_tests do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "15"
    scan(
      destination: DESTINATION,
      only_testing: [
        "UnitTests"
      ],
      output_directory: TEST_OUTPUT_DIRECTORY,
      output_types: "junit",
      result_bundle_path: RESULT_BUNDLE_PATH,
      skip_package_dependencies_resolution: true,
      test_without_building: true,
      xctestrun: "#{BUILD_OUTPUT_DIRECTORY}/settings.xctestrun"
    )
  end

  desc "Run ui tests without rebuilding"
  lane :run_ui_tests do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "15"
    scan(
      destination: DESTINATION,
      only_testing: [
        "UITests"
      ],
      output_directory: TEST_OUTPUT_DIRECTORY,
      output_types: "junit",
      result_bundle_path: RESULT_BUNDLE_PATH,
      skip_package_dependencies_resolution: true,
      test_without_building: true,
      xctestrun: "#{BUILD_OUTPUT_DIRECTORY}/settings.xctestrun"
    )
  end
end