# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Constant Values
BUILD_DATA_PATH = "build"
DERIVED_DATA_PATH = "derived_data"
DESTINATION = "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro"
PACKAGES_PATH = "packages_cache"
SCHEME = "FastlanePlayground"
WORKSPACE = "FastlanePlayground.xcworkspace"

platform :ios do
  desc "Build the iOS app"
  lane :build_tests do
    xcodebuild(
      buildlog_path: "#{BUILD_DATA_PATH}",
      configuration: "Debug",
      destination: "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro",
      scheme: SCHEME,
      workspace: WORKSPACE,
      xcargs: "-derivedDataPath #{DERIVED_DATA_PATH} -clonedSourcePackagesDirPath #{PACKAGES_PATH} build-for-testing"
    )
  end

  desc "Run unit tests without rebuilding"
  lane :run_unit_tests do
    scan(
      buildlog_path: "#{BUILD_DATA_PATH}",
      configuration: "Debug",
      derived_data_path: "#{DERIVED_DATA_PATH}",
      destination: "#{DESTINATION}",
      only_testing: [
        "UnitTests"
      ],
      output_types: "junit",
      scheme: SCHEME,
      test_without_building: true,
      cloned_source_packages_path: "#{PACKAGES_PATH}",
      disable_package_automatic_updates: true,
      workspace: WORKSPACE
    )
  end

  desc "Run uitests without rebuilding"
  lane :run_uitests do
    scan(
      buildlog_path: "#{BUILD_DATA_PATH}",
      configuration: "Debug",
      derived_data_path: "#{DERIVED_DATA_PATH}",
      destination: "#{DESTINATION}",
      only_testing: [
        "UITests"
      ],
      output_types: "junit",
      scheme:SCHEME,
      test_without_building: true,
      cloned_source_packages_path: "#{PACKAGES_PATH}",
      disable_package_automatic_updates: true,
      workspace: WORKSPACE
    )
  end
end