name: 'Setup iOS Environment'
description: 'Set up Ruby, Bundler, and install dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0

    - name: Switch to Xcode 16.2
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app
    
    - name: Cache Bundler Installation
      uses: actions/cache@v4
      with:
        path: .vendor/bundle
        key: bundler-cache-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
        restore-keys: bundler-cache-${{ runner.os }}-
    
    - name: Cache Derived Data
      id: cache-derived-data
      uses: actions/cache@v4
      with:
        path: derived_data
        key: derived-data-${{ runner.os }}-#${{ github.run_number }}
    
    - name: Cache SPM Data
      id: cache-spm-data
      uses: actions/cache@v4
      with:
        path: packages_cache
        key: packages-cache-${{ runner.os }}-${{ hashFiles('project.yml') }}
        restore-keys: packages-cache-${{ runner.os }}-
    
    - name: Cache Pod Data
      id: cache-pods-data
      uses: actions/cache@v4
      with:
        path: Pods
        key: pod-cache-${{ runner.os }}-${{ hashFiles('Podfile.lock') }}
        restore-keys: pod-cache-${{ runner.os }}-

    - name: Bootstrap
      shell: bash
      run: scripts/bootstrap.sh