name: Build Project for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Cache Bundler
        uses: ./.github/workflows/actions/cache-bundler

      - name: Cache Dependencies
        uses: ./.github/workflows/actions/cache-dependencies
      
      - name: Bootstrap
        shell: bash
        run: scripts/bootstrap.sh

      - name: Build Project
        run: bundle exec fastlane ios build_tests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_outputs
          path: build_outputs

  unit-tests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build_outputs
          path: build_outputs

      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Cache Bundler
        uses: ./.github/workflows/actions/cache-bundler

      - name: Cache Dependencies
        uses: ./.github/workflows/actions/cache-dependencies
      
      - name: Bootstrap
        shell: bash
        run: scripts/bootstrap.sh

      - name: Run Uint Tests
        run: bundle exec fastlane ios run_unit_tests
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_outputs
          path: test_outputs

  ui-tests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build_outputs
          path: build_outputs

      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Cache Bundler
        uses: ./.github/workflows/actions/cache-bundler

      - name: Cache Dependencies
        uses: ./.github/workflows/actions/cache-dependencies
      
      - name: Bootstrap
        shell: bash
        run: scripts/bootstrap.sh

      - name: Run UI Tests
        run: bundle exec fastlane ios run_ui_tests
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui_test_outputs
          path: test_outputs