name: Build Project for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Build Project
        run: bundle exec fastlane ios build_tests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: build

  unit-tests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Run Uint Tests
        run: bundle exec fastlane ios run_unit_tests
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit_tests_results
          path: outputs

  uitests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Run Uint Tests
        run: bundle exec fastlane ios run_uitests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uitests_results
          path: outputs