name: Build Project for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments

      - name: Build Project
        run: bundle exec fastlane ios build_tests

      - name: Cache DerivedData
        id: cache-derived-data
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: deriveddata-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

  unit-tests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments
        
      - name: Restore Cached DerivedData
        id: restore-derived-data
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: deriveddata-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Run Uint Tests
        run: bundle exec fastlane ios run_unit_tests

  uitests:
    runs-on: macos-15
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Environments
        uses: ./.github/workflows/actions/setup-environments
        
      - name: Restore Cached DerivedData
        id: restore-derived-data
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: deriveddata-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Run Uint Tests
        run: bundle exec fastlane ios run_uitests